# Generated by Django 4.0.3 on 2022-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
